// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

open class CompilerJsDceOptionsDsl (
    private val optionsAccessor: ((org.jetbrains.kotlin.gradle.dsl.CompilerJsDceOptions) -> Unit) -> Unit
)  : org.jetbrains.kotlin.gradle.dsl.CompilerCommonToolOptionsDsl(optionsAccessor) {

    /**
     * Development mode: don't strip out any code, just copy dependencies
     * Default value: false
     */
    fun devMode(value: kotlin.Boolean) {
        optionsAccessor { it.devMode.set(value) }
    }

    /**
     * Output directory
     * Default value: null
     */
    @Deprecated(message = "Use task 'destinationDirectory' to configure output directory", level = DeprecationLevel.WARNING)
    fun outputDirectory(value: kotlin.String?) {
        optionsAccessor { it.outputDirectory.set(value) }
    }
}
