// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

open class CompilerCommonToolOptionsDsl (
    private val optionsAccessor: ((org.jetbrains.kotlin.gradle.dsl.CompilerCommonToolOptions) -> Unit) -> Unit
)  {

    /**
     * Report an error if there are any warnings
     * Default value: false
     */
    fun allWarningsAsErrors(value: kotlin.Boolean) {
        optionsAccessor { it.allWarningsAsErrors.set(value) }
    }

    /**
     * Generate no warnings
     * Default value: false
     */
    fun suppressWarnings(value: kotlin.Boolean) {
        optionsAccessor { it.suppressWarnings.set(value) }
    }

    /**
     * Enable verbose logging output
     * Default value: false
     */
    fun verbose(value: kotlin.Boolean) {
        optionsAccessor { it.verbose.set(value) }
    }
}
