// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

open class CompilerMultiplatformCommonOptionsDsl (
    private val optionsAccessor: ((org.jetbrains.kotlin.gradle.dsl.CompilerMultiplatformCommonOptions) -> Unit) -> Unit
)  : org.jetbrains.kotlin.gradle.dsl.CompilerCommonOptionsDsl(optionsAccessor) {
}
