// DO NOT EDIT MANUALLY!
// Generated by org/jetbrains/kotlin/generators/arguments/GenerateGradleOptions.kt
// To regenerate run 'generateGradleOptions' task
@file:Suppress("RemoveRedundantQualifierName", "Deprecation", "DuplicatedCode")

package org.jetbrains.kotlin.gradle.dsl

open class CompilerCommonOptionsDsl (
    private val optionsAccessor: ((org.jetbrains.kotlin.gradle.dsl.CompilerCommonOptions) -> Unit) -> Unit
)  : org.jetbrains.kotlin.gradle.dsl.CompilerCommonToolOptionsDsl(optionsAccessor) {

    /**
     * Allow using declarations only from the specified version of bundled libraries
     * Possible values: "1.3 (deprecated)", "1.4 (deprecated)", "1.5", "1.6", "1.7", "1.8", "1.9 (experimental)"
     * Default value: null
     */
    fun apiVersion(value: org.jetbrains.kotlin.gradle.dsl.KotlinVersion?) {
        optionsAccessor { it.apiVersion.set(value) }
    }

    /**
     * Provide source compatibility with the specified version of Kotlin
     * Possible values: "1.3 (deprecated)", "1.4 (deprecated)", "1.5", "1.6", "1.7", "1.8", "1.9 (experimental)"
     * Default value: null
     */
    fun languageVersion(value: org.jetbrains.kotlin.gradle.dsl.KotlinVersion?) {
        optionsAccessor { it.languageVersion.set(value) }
    }

    /**
     * Compile using experimental K2. K2 is a new compiler pipeline, no compatibility guarantees are yet provided
     * Default value: false
     */
    fun useK2(value: kotlin.Boolean) {
        optionsAccessor { it.useK2.set(value) }
    }
}
